name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run checks
        run: bash scripts/check.sh
