name: release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build model
        run: rojo build default.project.json -o SwiftPacket.rbxm

      - name: Upload model
        run: gh release upload ${{ github.event.release.tag_name }} SwiftPacket.rbxm --clobber
